replicaCount: 1

image:
  repository: 715923838470.dkr.ecr.ap-southeast-1.amazonaws.com/product-service
  tag: latest

service:
  type: ClusterIP
  port: 3002

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::715923838470:role/ecommerce-product-service-role"

config:
  NODE_ENV: production
  PORT: "3002"
  DATABASE_HOST: "ecommerce-postgres.c7gyqes8qujb.ap-southeast-1.rds.amazonaws.com"
  DATABASE_PORT: "5432"
  DATABASE_NAME: product_db
  DATABASE_USER: postgres
  AWS_REGION: ap-southeast-1
  S3_MEDIA_BUCKET: "ecommerce-product-images-715923838470"
  CLOUDFRONT_URL: "https://d2sk3hc934h1p6.cloudfront.net"

externalSecret:
  enabled: false
  secretPath: /ecommerce/product-service
  keys:
    - secretKey: DATABASE_PASSWORD
      property: DATABASE_PASSWORD
    - secretKey: JWT_ACCESS_SECRET
      property: JWT_ACCESS_SECRET
