image:
  tag: develop-24-2b36dac

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

config:
  NODE_ENV: production
  DATABASE_NAME: product_db_dev
  CLOUDFRONT_URL: "https://d1q28g8lb2x75x.cloudfront.net"
  S3_MEDIA_BUCKET: "ecommerce-product-images-715923838470"
  S3_KEY_PREFIX: "dev"

externalSecret:
  enabled: false
  secretPath: /ecommerce/product-service
