replicaCount: 1

image:
  repository: 715923838470.dkr.ecr.ap-southeast-1.amazonaws.com/payment-service
  tag: latest

service:
  type: ClusterIP
  port: 3004

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::715923838470:role/ecommerce-payment-service-role"

config:
  NODE_ENV: production
  PORT: "3004"
  DATABASE_HOST: "ecommerce-postgres.c7gyqes8qujb.ap-southeast-1.rds.amazonaws.com"
  DATABASE_PORT: "5432"
  DATABASE_NAME: payment_db
  DATABASE_USER: postgres
  AWS_REGION: ap-southeast-1
  SQS_ORDER_CREATED_URL: "https://sqs.ap-southeast-1.amazonaws.com/715923838470/ecommerce-order-created"
  SNS_ORDER_PAID_TOPIC_ARN: "arn:aws:sns:ap-southeast-1:715923838470:ecommerce-order-paid"

externalSecret:
  enabled: false
  secretPath: /ecommerce/payment-service
  keys:
    - secretKey: DATABASE_PASSWORD
      property: DATABASE_PASSWORD
    - secretKey: JWT_ACCESS_SECRET
      property: JWT_ACCESS_SECRET
