image:
  tag: latest-dev

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

config:
  NODE_ENV: development
  DATABASE_NAME: order_db_dev

externalSecret:
  enabled: false
  secretPath: /ecommerce/order-service
