replicaCount: 1

image:
  repository: 715923838470.dkr.ecr.ap-southeast-1.amazonaws.com/user-service
  tag: latest

service:
  type: ClusterIP
  port: 3001

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

serviceAccount:
  annotations:
    eks.amazonaws.com/role-arn: "arn:aws:iam::715923838470:role/ecommerce-user-service-role"

config:
  NODE_ENV: production
  PORT: "3001"
  DATABASE_HOST: "ecommerce-postgres.c7gyqes8qujb.ap-southeast-1.rds.amazonaws.com"
  DATABASE_PORT: "5432"
  DATABASE_NAME: user_db
  DATABASE_USER: postgres
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  AWS_REGION: ap-southeast-1
  SNS_USER_REGISTERED_TOPIC_ARN: "arn:aws:sns:ap-southeast-1:715923838470:ecommerce-user-registered"

externalSecret:
  enabled: false
  secretPath: /ecommerce/user-service
  keys:
    - secretKey: DATABASE_PASSWORD
      property: DATABASE_PASSWORD
    - secretKey: JWT_ACCESS_SECRET
      property: JWT_ACCESS_SECRET
    - secretKey: JWT_REFRESH_SECRET
      property: JWT_REFRESH_SECRET
