replicaCount: 1

image:
  repository: 715923838470.dkr.ecr.ap-southeast-1.amazonaws.com/frontend
  tag: latest

service:
  type: ClusterIP
  port: 3005

resources:
  requests:
    cpu: 200m
    memory: 512Mi
  limits:
    cpu: 1000m
    memory: 1Gi

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: /
  host: ""

config:
  NODE_ENV: production
  PORT: "3005"
  API_URL: "http://api-gateway:3000"
  # Điền sau khi api-gateway ALB được tạo — xem: kubectl get ingress -n ecommerce
  NEXT_PUBLIC_API_URL: "http://k8s-ecommerc-apigatew-bac50f6700-113943684.ap-southeast-1.elb.amazonaws.com"

externalSecret:
  enabled: false
