image:
  tag: develop-17-232ea16

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  NODE_ENV: development
  # Cập nhật sau khi deploy lần đầu: kubectl get ingress -n ecommerce-dev
  NEXT_PUBLIC_API_URL: "http://k8s-ecommerc-apigatew-afc7d5cc0d-1740156965.ap-southeast-1.elb.amazonaws.com"

externalSecret:
  enabled: false
