image:
  tag: develop-30-95b72e3

replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

config:
  NODE_ENV: development
  # SSR server-side dùng internal K8s service (không qua ALB)
  API_URL: "http://api-gateway-dev:3000"
  # Client-side browser dùng ALB URL (cập nhật nếu ALB thay đổi)
  NEXT_PUBLIC_API_URL: "http://k8s-ecommerc-apigatew-afc7d5cc0d-1740156965.ap-southeast-1.elb.amazonaws.com"

externalSecret:
  enabled: false
