image:
  tag: develop-21-52c05d8

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

config:
  NODE_ENV: development
  CORS_ORIGIN: "http://k8s-ecommerc-frontend-098809d8ea-1169492521.ap-southeast-1.elb.amazonaws.com"
  USER_SERVICE_URL: "http://user-service-dev:3001"
  PRODUCT_SERVICE_URL: "http://product-service-dev:3002"
  ORDER_SERVICE_URL: "http://order-service-dev:3003"
  PAYMENT_SERVICE_URL: "http://payment-service-dev:3004"

externalSecret:
  enabled: false
  secretPath: /ecommerce/api-gateway
