image:
  tag: develop-11-f41e124

replicaCount: 1

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi

config:
  NODE_ENV: development
  # Cập nhật sau khi deploy lần đầu: kubectl get ingress -n ecommerce-dev
  CORS_ORIGIN: "http://k8s-ecommerc-frontend-098809d8ea-1169492521.ap-southeast-1.elb.amazonaws.com"

externalSecret:
  enabled: false
  secretPath: /ecommerce/api-gateway
